zalando-incubator/fabric-gateway

MAINTAINERS

Update maintainers list

---

.github/workflows/scala.yml

Add action to test build in public

---

src/it/resources/wiremock/__files/stack-set.json
src/it/scala/ie/zalando/fabric/gateway/TestJsonModels.scala
src/main/scala/ie/zalando/fabric/gateway/models/HttpModels.scala
src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/main/scala/ie/zalando/fabric/gateway/service/StackSetOperations.scala
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala

* Change StackSet spec to match actual
* Update serialization logic for servicePort to be String or Int

MID-2111: Test StackSet Integration

---

README.md

Fix Image link

---

docs-raw/site/docs/fabric-gateway-features.md

* Update docs with details around StackSet integration

MID-2111: StackSet Integration Documentation

---

src/main/scala/ie/zalando/fabric/gateway/web/tracing/TracingSupport.scala

MID-2111: Add tracing support

---

README.md

Forgot to re-add this when switching how the versioned hosts are configured

Document env var

---

docs-raw/site/docs/fabric-gateway-features.md

Adds documentation for the stackset versioned-hosts feature.

Document versioned hosts

---

docs-raw/site/docs/fabric-gateway-features.md
src/it/scala/ie/zalando/fabric/gateway/ApiValidationSpec.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala

It seems to have been removed at some point

Re-add admin audit filter

---

src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala

* Add the AccessLogAudit filter into the whitelist rejection routes

MID-2573: Service Auditing not happening for whitelist rejection routes

---

dev/testing/README.md
dev/testing/stackSetIntegration/gateway.yaml

Make tests easier to run, fix lint issues, add test for fractional weights. Follow up work for https://github.com/zalando-incubator/fabric-gateway/pull/33

Make tests easier to run, fix lint issues, add test for fractional weights

---

src/it/resources/synch/synchRequestWhichTriggersInvalidStackSetResponse.json
src/it/resources/wiremock/__files/stack-set-with-bad-status.json
src/it/resources/wiremock/mappings/validStackSetQueryWithInvalidTrafficStatus.json
src/it/scala/ie/zalando/fabric/gateway/ApiValidationSpec.scala
src/it/scala/ie/zalando/fabric/gateway/TestUtils.scala
src/main/scala/ie/zalando/fabric/gateway/service/StackSetOperations.scala

* StackSet retrieval failures other than 404 should not cause the Gateway to remove routes

MID-2606: Improve StackSet support in Gateway

---

src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala

* Using route weighting algorithm to separate routes
* Fix tests to incorporate weight check

MID-2836: Route Weights

---

deploy/operator/apply/01_FabricGatewayCRD.yaml
src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala
src/test/scala/ie/zalando/fabric/gateway/service/ZeroDowntimeIngressTransitionsSpec.scala

* Update CRD to remove requirement for user-list in `x-fabric-employeeaccess` key
* Update user access logic to allow global access

MID-2766: Employee Global Access

---

delivery.yaml
deploy/operator/apply/07_OperatorDeployment.yaml
src/main/resources/application.conf
src/main/scala/ie/zalando/fabric/gateway/config/AppConfig.scala
src/main/scala/ie/zalando/fabric/gateway/config/TracingConfig.scala
src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/resources/application.conf
src/test/resources/logback.xml
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala
src/test/scala/ie/zalando/fabric/gateway/service/ZeroDowntimeIngressTransitionsSpec.scala

* Add in annotation passthrough logic
* Add testable annotations for playground

MID-2789: Allowlist for Annotation Passthrough

---

deploy/operator/apply/01_FabricGatewayCRD.yaml
src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala
src/main/scala/ie/zalando/fabric/gateway/service/IngressDerivationChain.scala
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala
src/test/scala/ie/zalando/fabric/gateway/service/ZeroDowntimeIngressTransitionsSpec.scala

* Allow defining Employee Access at a global level
* Allow to define Deny All Employee Access to routes

MID-2917: Employee Access Improvements

---

deploy/operator/apply/01_FabricGatewayCRD.yaml

* Some documentation changes made. re-Synching

MID-000: Re-Synch CRD

---

deploy/operator/apply/02_GatewayCRDSchemaValidation.yaml
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/scala/ie/zalando/fabric/gateway/service/web/marshalling/IngressMarshallingSpec.scala

* Model the pathType for a backend to avoid triggering diffs in metacontroller

MID-2994: Prevent Excessive Updates

---

docker/e2e/Dockerfile
docker/svc/Dockerfile

Update base images

---

deploy/test-app/apply/TestAppGateway.yaml
src/e2e/scala/ie/zalando/fabric/gateway/spec/CorsSpec.scala
src/main/scala/ie/zalando/fabric/gateway/service/ResourcePersistenceValidations.scala
src/main/scala/ie/zalando/fabric/gateway/util/Util.scala
src/main/scala/ie/zalando/fabric/gateway/web/marshalling/JsonModels.scala
src/test/scala/ie/zalando/fabric/gateway/service/IngressDerivationChainSpec.scala
src/test/scala/ie/zalando/fabric/gateway/service/ValidationSpec.scala

Signed-off-by: Conor Gallagher <conor.gallagher@zalando.ie>

Fixing validation of Cors hostname string

---

src/main/scala/ie/zalando/fabric/gateway/models/SynchDomain.scala

Minute should not be referenced as the time-unit is configurable

Fixing Rate limiting message

---

README.md

Signed-off-by: Conor Gallagher <conor.gallagher@zalando.ie>

Trigger fresh build and commit message for four-eyes approval

---

docs-raw/site/docs/fabric-gateway-features.md
src/e2e/scala/ie/zalando/fabric/gateway/spec/RejectHttpSpec.scala

* Update e2e test to expect a redirect for http traffic as opposed to a 400

Handle NLB Changes
